// <auto-generated />
namespace DABAB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class MovieCommentTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieCommentTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202007040956091_MovieCommentTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
